---
- name: Add MongoDB in package manager
  become: yes
  copy:
    src: mongodb-org-4.2.repo
    dest: /etc/yum.repos.d/mongodb-org-4.2.repo

- name: Install PyMongo
  pip:
    name: pymongo

- name: Install MongoDB
  yum:
    name: "mongodb-org"
    state: installed

- name: Update MongoDB config file
  become: yes
  copy:
    src: mongod.conf
    dest: /etc/mongod.conf
  notify: "Restart MongoDB"

- name: Force MongoDB to restart
  meta: flush_handlers

- name: Add host for HA
  mongo_ha:
    hosts:
      - mongodb0
      - mongodb1
      - mongodb2
    delayed_members:
      - mongodb2:
        delay: 5
  run_once: yes
