---
- name: Add MongoDB in package manager
  become: yes
  copy:
    src: mongodb-org-4.2.repo
    dest: /etc/yum.repos.d/mongodb-org-4.2.repo

- name: Install EPEL
  become: yes
  yum:
    name: "epel-release"

- name: Install Python and Pip
  become: yes
  yum:
    name: ["python", "python-pip"]

- name: Install PyMongo
  become: yes
  pip:
    name: pymongo

- name: Install MongoDB
  become: yes
  yum:
    name: "mongodb-org"
    state: installed

- name: Update MongoDB config file
  become: yes
  copy:
    src: mongod.conf
    dest: /etc/mongod.conf
  notify: "Restart MongoDB"

- name: Force MongoDB to restart
  meta: flush_handlers

- name: Add hosts for HA
  mongo_ha:
    hosts:
      - "{{ groups['mongodb0'][0] }}"
      - "{{ groups['mongodb1'][0] }}"
      - "{{ groups['mongodb2'][0] }}"
    delayed_members:
      "{{ groups['mongodb2'][0] }}":
        delay: 5
  run_once: yes
