---
- hosts: postgres
  become: yes
  gather_facts: no

  tasks:
  - name: ensure apt cache is up to date
    apt: update_cache=yes
  - name: ensure packages are installed
    apt: name={{item}} state=latest
    with_items:
        - postgresql
        - libpq-dev
        - python3-psycopg2

