FROM fedora

EXPOSE 27017

COPY files/mongodb-org-4.2.repo /etc/yum.repos.d/mongodb-org-4.2.repo

RUN yum install -y mongodb-org

COPY configure configure
COPY configure2 configure2

CMD ["bash", "./configure2"]
