
version: '3.1'

services:
    mongodb_master:
     build:
       context: .
       dockerfile: Dockerfile-master
     image: mongodb
     volumes:
       - db_data_master:/var/lib/mongo
     ports:
       - "27017:27017"
     restart: always
     networks:
       mongodb:
         aliases:
           - master
    mongodb_slave1:
     depends_on:
      - mongodb_master
     build:
       context: .
       dockerfile: Dockerfile-master
     image: mongodb
     volumes:
       - db_data_slave1:/var/lib/mongo
     ports:
       - "27018:27017"
     restart: always
     networks:
       mongodb:
         aliases:
           - slave1
    mongodb_slave2:
     depends_on:
      - mongodb_slave1
     build:
       context: .
       dockerfile: Dockerfile-master
     image: mongodb
     volumes:
       - db_data_slave2:/var/lib/mongo
     ports:
       - "27019:27017"
     restart: always
     networks:
       mongodb:
         aliases:
           - slave2
    replicat_init:
     depends_on:
      - mongodb_slave2
     build:
       context: .
       dockerfile: Dockerfile-replica
     image: replicat_init
     restart: "no"
     networks:
       mongodb:
         aliases:
           - replicat_init

volumes:
  db_data_master: {}
  db_data_slave1: {}
  db_data_slave2: {}

networks:
  mongodb:
    driver: bridge
