- name: Allow PostgreSQL RPM repository
  yum:
    name: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
    state: present

- name: Install PostgreSQL
  yum:
    name: ["postgresql11", "postgresql11-server", "python-psycopg2"]
    state: present
  notify: "Init PostgreSQL"

- name: Force init PostgreSQL
  meta: flush_handlers

- name: Update pg_hba.conf
  template:
    src: "pg_hba.conf"
    dest: "/var/lib/pgsql/11/data/pg_hba.conf"
    owner: postgres
    group: postgres

- name: Start and enabled PostgreSQL
  systemd:
    name: postgresql-11
    state: started
    enabled: yes

- name: ensure database is created
  become: yes
  become_user: postgres
  postgresql_db:
    name: postgres

- name: Create rails user
  become: yes
  become_user: postgres
  postgresql_user:
    db: postgres
    name: rails
    password: password
    role_attr_flags: NOSUPERUSER

- name: Upload test file for rails users
  template:
    src: "tests/user_create.j2"
    dest: "/"
    owner: postgres
    group: postgres
    mode: a+x
  when: debug|bool
