- name: Allow PostgreSQL RPM repository
  yum:
    name: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
    state: present

- name: Install PostgreSQL
  yum:
    name: "postgresql11,postgresql11-server"
    state: present
  notify: [ "Init PostgreSQL", "Start and enabled PostgreSQL" ]
